/*
 * Configuration for voyager - DO NOT EDIT THIS FILE BY HAND!
 *
 * NOTE WELL: Your project MUST have a voyager_cfgport.h - even if
 *            it's empty!!!
 *
 * Refer to the notes below for details on the voyager configuration
 * options.
 */

#ifndef _VOYAGER_CFG_H
#define _VOYAGER_CFG_H

/*
 * There are a number of defines you can set at compile time that affect how
 * the voyager bootloader will operate.
 *
 * You should NOT edit this file, it may be changed from time to time in
 * the upstream project. Instead, you can do one of the following (in order
 * of priority
 *
 * 1. Pass in the override values on the command line using:
 *     -D VOYAGER_BOOTLOADER_xxx
 *
 * 2. Pass in the filename holding override values using:
 *     -D VOYAGER_CFGFILE
 *
 * 3. Set up defaults in a file called:
 *     voyager_cfgport.h
 *
 * NOTE WELL: For the command line -D options to take highest priority, your
 *            project level override file must check that the
 *            VOYAGER_BOOTLOADER_xxx value is not already defined before
 *            overriding the value.
 *
 * Unless otherwise noted, the default state of these values is #undef-ined!
 * ----------------------------------------------------------------------------
 */

#ifdef VOYAGER_CFGFILE
#include VOYAGER_CFGFILE
#else
#include <voyager_cfgport.h>
#endif

/* Only override if it's not already defined */

#ifndef VOYAGER_BOOTLOADER_MAX_RECEIVE_PACKET_SIZE
// Do nothing - the voyager_priv.h file lets us know if it's undefined
// or the wrong size
#endif

#endif /* _VOYAGER_CFG_H */